---------------------------------------------------------------------------------
----
----		Cutscene am Ende von Gate of Swords, Shadowsong und Eisenfürst schliessen sich an
----
---------------------------------------------------------------------------------
--
--
--State
--{
--	StateName = "Init",
--	OnOneTimeEvent
--	{
--		GotoState = "CutsceneGate",
--		Conditions =
--		{
--			MapFlagIsTrue  {Name = "mf_P309_HotchKissTalked"},
--			AvatarIsNotTalking{}, GameInterfaceIsVisible{}, -- die beiden gehören zusammen, deswegen beide in einer zeile!
--		},
--		Actions =
--		{
--			
--		},
--	},
--}
--
--
--
--State
--{
--	StateName = "CutsceneGate",
--	
--	OnOneTimeEvent
--	{
--		Conditions =
--		{  
--		},
--		Actions = 
--		{
--			CutsceneBegin {},
--			CameraSet {X = 574.72, Y = 49.32, Z = 317.26, LookAtX = 575.00, LookAtY = 48.49, LookAtZ = 318.16},
--			EntityTimerStart {Name = "et_CutsceneGateEnd"},
--		},
--		
--	},
--	
--	OnOneTimeEvent
--	{
--			Conditions =
--			{
--				EntityTimerIsElapsed {Name = "et_CutsceneGateEnd", Seconds = 4},
--			},
--			Actions =
--			{
--				CutsceneSay	{TextTag = "Avatar8", Tag = "pl_HumanAvatar"},
--			},
--	},
--	OnOneTimeEvent
--	{
--			Conditions =
--			{
--				EntityTimerIsElapsed {Name = "et_CutsceneGateEnd", Seconds = 10},
--			},
--			Actions =
--			{
--				CutsceneSay	{TextTag = "Ironlord6", Tag = "Ironlord"},
--			},
--	},
--	OnOneTimeEvent
--	{
--			Conditions =
--			{
--				EntityTimerIsElapsed {Name = "et_CutsceneGateEnd", Seconds = 16},
--			},
--			Actions =
--			{
--				CutsceneSay	{TextTag = "StoneGod1", Tag = "StoneGod"},
--			},
--	},
--	OnOneTimeEvent
--	{
--			Conditions =
--			{
--				EntityTimerIsElapsed {Name = "et_CutsceneGateEnd", Seconds = 20},
--			},
--			Actions =
--			{
--				CutsceneSay	{TextTag = "StoneGod2", Tag = "StoneGod"},
--			},
--	},
--	OnOneTimeEvent
--	{
--			Conditions =
--			{
--				EntityTimerIsElapsed {Name = "et_CutsceneGateEnd", Seconds = 24},
--			},
--			Actions =
--			{
--				CutsceneSay	{TextTag = "StoneGod3", Tag = "StoneGod"},
--			},
--	},
--	OnOneTimeEvent
--	{
--			Conditions =
--			{
--				EntityTimerIsElapsed {Name = "et_CutsceneGateEnd", Seconds = 29},
--			},
--			Actions =
--			{
--				CutsceneSay	{TextTag = "Avatar9", Tag = "pl_HumanAvatar"},
--			},
--	},
--	OnOneTimeEvent
--	{
--			Conditions =
--			{
--				EntityTimerIsElapsed {Name = "et_CutsceneGateEnd", Seconds = 33},
--			},
--			Actions =
--			{
--				CutsceneSay	{TextTag = "IronLord7", Tag = "IronLord"},
--			},
--	},
--	OnOneTimeEvent
--	{
--			Conditions =
--			{
--				EntityTimerIsElapsed {Name = "et_CutsceneGateEnd", Seconds = 37},
--			},
--			Actions =
--			{
--				CameraStop {},				
--				CutsceneEnd {}, 
--				AvatarFlagSetTrue {Name = "af_P309_CutsceneGateEndEnd"},
--				QuestSetActive {Quest = "NightsongMustLiveTilShal"},
--				QuestSetActive {Quest = "IronLordMustLive"},
--				QuestSetActive {Quest = "GoSPart9MarchToDraghLur"},
--			},
--	},
--};

	
