---------------------------------------------------------------------------------
----
----		Cutscene bei Missionsbeginn
----
---------------------------------------------------------------------------------
--
--
--State
--{
--	StateName = "Init",
--	OnOneTimeEvent
--	{
--		GotoState = "Cutscene3",
--		Conditions =
--		{
--			MapFlagIsTrue {Name = "mf_P301_CutsceneLyasAlive"},
--		},
--		Actions =
--		{
--			
--		},
--	},
--}
--
--
--
--State
--{
--	StateName = "Cutscene3",
--	
--	OnOneTimeEvent
--	{
--		Conditions =
--		{  
--		},
--		Actions = 
--		{
--			CutsceneBegin {},
--			CameraSet {X = 568.64, Y = 61.67, Z = 417.23, LookAtX = 567.71, LookAtY = 61.23, LookAtZ = 417.11},
--			EntityTimerStart {Name = "et_Cutscene3"},
--		},
--		
--	},
--	
--	OnOneTimeEvent
--	{
--			Conditions =
--			{
--				EntityTimerIsElapsed {Name = "et_Cutscene3", Seconds = 4},
--			},
--			Actions =
--			{
--				CutsceneSay	{TextTag = "Lya1", Tag = "Lya"},
--			},
--	},
--	OnOneTimeEvent
--	{
--			Conditions =
--			{
--				EntityTimerIsElapsed {Name = "et_Cutscene3", Seconds = 10},
--			},
--			Actions =
--			{
--				CutsceneSay	{TextTag = "Bor9", Tag = "Bor"},
--			},
--	},
--	OnOneTimeEvent
--	{
--			Conditions =
--			{
--				EntityTimerIsElapsed {Name = "et_Cutscene3", Seconds = 16},
--			},
--			Actions =
--			{
--				CutsceneSay	{TextTag = "Lya2", Tag = "Lya"},
--			},
--	},
--	OnOneTimeEvent
--	{
--			Conditions =
--			{
--				EntityTimerIsElapsed {Name = "et_Cutscene3", Seconds = 20},
--			},
--			Actions =
--			{
--				CutsceneSay	{TextTag = "Bor10", Tag = "Bor"},
--			},
--	},
--	OnOneTimeEvent
--	{
--			Conditions =
--			{
--				EntityTimerIsElapsed {Name = "et_Cutscene3", Seconds = 24},
--			},
--			Actions =
--			{
--				CutsceneSay	{TextTag = "Lya3", Tag = "Lya"},
--			},
--	},
--	OnOneTimeEvent
--	{
--			Conditions =
--			{
--				EntityTimerIsElapsed {Name = "et_Cutscene3", Seconds = 29},
--			},
--			Actions =
--			{
--				CutsceneSay	{TextTag = "Bor11", Tag = "Bor"},
--			},
--	},
--	OnOneTimeEvent
--	{
--			Conditions =
--			{
--				EntityTimerIsElapsed {Name = "et_Cutscene3", Seconds = 34},
--			},
--			Actions =
--			{
--				CutsceneSay	{TextTag = "Lya4", Tag = "Lya"},
--			},
--	},
--	OnOneTimeEvent
--	{
--			Conditions =
--			{
--				EntityTimerIsElapsed {Name = "et_Cutscene3", Seconds = 40},
--			},
--			Actions =
--			{
--				CameraStop {},				
--				CutsceneEnd {},
--				QuestSetSolved {Quest = "ReviveLya"},
--				QuestSetSolved {Quest = "IronFieldsPart1Lya"},
--				QuestSetActive {Quest = "IronFieldsPart2WarnFortress"},
--				MapFlagSetTrue {Name = "mf_P301_CutsceneLyasAliveShown"},
--				AvatarXPGive {Amount = 200}
--			},
--	},
--};