---------------------------------------------------------------------------------
----
----		Cutscene bei Missionsbeginn
----
---------------------------------------------------------------------------------
--
--
--State
--{
--	StateName = "Init",
--	OnOneTimeEvent
--	{
--		GotoState = "Cutscene12",
--		Conditions =
--		{
--			FigureIsInEntityRange	{Tag = "Hydra", TargetTag = "pl_HumanAvatar", Range = 10},
--			QuestIsActive {Quest = "KillHydra"},
--		},
--		Actions =
--		{
--			
--		},
--	},
--}
--
--
--
--State
--{
--	StateName = "Cutscene12",
--	
--	OnOneTimeEvent
--	{
--		Conditions =
--		{  
--		},
--		Actions = 
--		{
--			CutsceneBegin {},
--			CameraSet {X = 568.64, Y = 61.67, Z = 417.23, LookAtX = 567.71, LookAtY = 61.23, LookAtZ = 417.11},
--			EntityTimerStart {Name = "et_Cutscene12"},
--		},
--		
--	},
--	
--	OnOneTimeEvent
--	{
--			Conditions =
--			{
--				EntityTimerIsElapsed {Name = "et_Cutscene12", Seconds = 4},
--			},
--			Actions =
--			{
--				CutsceneSay	{TextTag = "Hydra2", Tag = "Hydra"},
--			},
--	},
--	OnOneTimeEvent
--	{
--			Conditions =
--			{
--				EntityTimerIsElapsed {Name = "et_Cutscene12", Seconds = 10},
--			},
--			Actions =
--			{
--				CutsceneSay	{TextTag = "Avatar19", Tag = "pl_HumanAvatar"},
--			},
--	},
--	OnOneTimeEvent
--	{
--			Conditions =
--			{
--				EntityTimerIsElapsed {Name = "et_Cutscene12", Seconds = 16},
--			},
--			Actions =
--			{
--				CutsceneSay	{TextTag = "Hydra3", Tag = "Hydra"},
--			},
--	},
--	OnOneTimeEvent
--	{
--			Conditions =
--			{
--				EntityTimerIsElapsed {Name = "et_Cutscene12", Seconds = 20},
--			},
--			Actions =
--			{
--				CutsceneSay	{TextTag = "Hydra4", Tag = "Hydra"},
--			},
--	},
--	OnOneTimeEvent
--	{
--			Conditions =
--			{
--				EntityTimerIsElapsed {Name = "et_Cutscene12", Seconds = 24},
--			},
--			Actions =
--			{
--				CutsceneSay	{TextTag = "Hydra5", Tag = "Hydra"},
--			},
--	},
--	OnOneTimeEvent
--	{
--			Conditions =
--			{
--				EntityTimerIsElapsed {Name = "et_Cutscene12", Seconds = 29},
--			},
--			Actions =
--			{
--				CutsceneSay	{TextTag = "Avatar20", Tag = "pl_HumanAvatar"},
--			},
--	},
--	OnOneTimeEvent
--	{
--			Conditions =
--			{
--				EntityTimerIsElapsed {Name = "et_Cutscene12", Seconds = 34},
--			},
--			Actions =
--			{
--				CutsceneSay	{TextTag = "Hydra6", Tag = "Hydra"},
--			},
--	},
--	OnOneTimeEvent
--	{
--			Conditions =
--			{
--				EntityTimerIsElapsed {Name = "et_Cutscene12", Seconds = 40},
--			},
--			Actions =
--			{
--				CutsceneSay	{TextTag = "NightSong11", Tag = "NightSong"},
--			},
--	},
--	OnOneTimeEvent
--	{
--			Conditions =
--			{
--				EntityTimerIsElapsed {Name = "et_Cutscene12", Seconds = 46},
--			},
--			Actions =
--			{
--				CutsceneSay	{TextTag = "Avatar21", Tag = "pl_HumanAvatar"},
--			},
--	},
--	OnOneTimeEvent
--	{
--			Conditions =
--			{
--				EntityTimerIsElapsed {Name = "et_Cutscene12", Seconds = 50},
--			},
--			Actions =
--			{
--				CameraStop {},				
--				CutsceneEnd {}, 
--				FigureTeamTransfer {Tag = "Hydra", Team = "tm_Team3"}
--			},
--	},
--};
--
--	
