---------------------------------------------------------------------------------
----
----		Cutscene bei Missionsbeginn
----
---------------------------------------------------------------------------------
--
--
--State
--{
--	StateName = "Init",
--	OnOneTimeEvent
--	{
--		GotoState = "Cutscene11",
--		Conditions =
--		{
--			QuestIsSolved {Quest = "AwakeTreants"},
--			AvatarIsNotTalking{}, GameInterfaceIsVisible{}, -- die beiden gehören zusammen, deswegen beide in einer zeile!
--		},
--		Actions =
--		{
--			
--		},
--	},
--}
--
--
--
--State
--{
--	StateName = "Cutscene11",
--	
--	OnOneTimeEvent
--	{
--		Conditions =
--		{  
--		},
--		Actions = 
--		{
--			CutsceneBegin {},
--			CameraSet {X = 568.64, Y = 61.67, Z = 417.23, LookAtX = 567.71, LookAtY = 61.23, LookAtZ = 417.11},
--			EntityTimerStart {Name = "et_Cutscene11"},
--		},
--		
--	},
--	
--	OnOneTimeEvent
--	{
--			Conditions =
--			{
--				EntityTimerIsElapsed {Name = "et_Cutscene11", Seconds = 4},
--			},
--			Actions =
--			{
--				CutsceneSay	{TextTag = "Grimrot1", Tag = "Grimrot"},
--			},
--	},
--	OnOneTimeEvent
--	{
--			Conditions =
--			{
--				EntityTimerIsElapsed {Name = "et_Cutscene11", Seconds = 10},
--			},
--			Actions =
--			{
--				CutsceneSay	{TextTag = "Grimrot2", Tag = "Grimrot"},
--			},
--	},
--	OnOneTimeEvent
--	{
--			Conditions =
--			{
--				EntityTimerIsElapsed {Name = "et_Cutscene11", Seconds = 16},
--			},
--			Actions =
--			{
--				CutsceneSay	{TextTag = "Grimrot3", Tag = "Grimrot"},
--			},
--	},
--	OnOneTimeEvent
--	{
--			Conditions =
--			{
--				EntityTimerIsElapsed {Name = "et_Cutscene11", Seconds = 20},
--			},
--			Actions =
--			{
--				CutsceneSay	{TextTag = "Avatar17", Tag = "pl_HumanAvatar"},
--			},
--	},
--	OnOneTimeEvent
--	{
--			Conditions =
--			{
--				EntityTimerIsElapsed {Name = "et_Cutscene11", Seconds = 24},
--			},
--			Actions =
--			{
--				CutsceneSay	{TextTag = "Grimrot4", Tag = "Grimrot"},
--			},
--	},
--	OnOneTimeEvent
--	{
--			Conditions =
--			{
--				EntityTimerIsElapsed {Name = "et_Cutscene11", Seconds = 29},
--			},
--			Actions =
--			{
--				CutsceneSay	{TextTag = "Avatar18", Tag = "pl_HumanAvatar"},
--			},
--	},
--	OnOneTimeEvent
--	{
--			Conditions =
--			{
--				EntityTimerIsElapsed {Name = "et_Cutscene11", Seconds = 34},
--			},
--			Actions =
--			{
--				CutsceneSay	{TextTag = "Grimrot5", Tag = "Grimrot"},
--			},
--	},
--	OnOneTimeEvent
--	{
--			Conditions =
--			{
--				EntityTimerIsElapsed {Name = "et_Cutscene11", Seconds = 40},
--			},
--			Actions =
--			{
--				CutsceneSay	{TextTag = "Grimrot6", Tag = "Grimrot"},
--			},
--	},
--	OnOneTimeEvent
--	{
--			Conditions =
--			{
--				EntityTimerIsElapsed {Name = "et_Cutscene11", Seconds = 60},
--			},
--			Actions =
--			{
--				CameraStop {},				
--				CutsceneEnd {}, 
--				MapTimerStart {Name = "mt_P301_OutcriesAfterDragonFight"},
--				FigurePlayerTransfer {Tag = "Tree1"},
--				FigurePlayerTransfer {Tag = "Tree2"},
--				FigurePlayerTransfer {Tag = "Tree3"},
--				FigurePlayerTransfer {Tag = "Grimrot"},
--				PlayerKitTransfer {PlayerKit = "pk_Elenshrine"},
--				DialogSetDisabled {Tag = "IoMission"},
--				FigureOutcry {TextTag = "TothLar1", Tag = "TothLar"},
--			},
--	},
--};
--
--	
