--
--
----Object/UnitIds
--local LightId = 1254
--local NoLightId = 1340 
--local Fire = 611
--
--
--State
--{
--	StateName = "OrogLightsInit",
--   	OnOneTimeEvent
--	{
--    	
--    	Conditions =
--    	{
--    	
--    	},
--    	Actions =
--    	{
--    		MapFlagSetTrue {Name = "mf_OrogLight05On"},
--       	},
--		GotoState = "OrogLight05Start"
--	},
--}
--
--State	
--{
--    StateName = "OrogLight05Start",
--    --An und Ausschalten der Fackeln
--    --OrogLight ausschalten
--   
--    OnEvent
--    {
--    	
--    	Conditions =
--    	{
--			SetUpdateInterval {Steps = 6},
--    		MapFlagIsTrue {Name = "mf_OrogLight05On"},
--    		FigureIsInRange	{Tag = "pl_HumanAvatar", Range = 2, X = GetEntityX(), Y = GetEntityY()},
--    	},
--    	Actions =
--    	{
-- 			ObjectChange	{Tag = "OrogLight05", ObjectId = NoLightId, X = GetEntityX(), Y = GetEntityY()},
-- 			MapFlagSetFalse {Name = "mf_OrogLight05On"},
-- 			MapTimerStart	{Name = "mt_Burner05generateTimer"},
--   		},
--    },   
--    --OrogLight einschalten
--    OnEvent
--    {
--    	
--    	Conditions =
--    	{
--			SetUpdateInterval {Steps = 6},
--    		MapFlagIsFalse {Name = "mf_OrogLight05On"},
--    		FigureUnitNpcIsInRange	{UnitId = Fire, Range = 2, X = GetEntityX(), Y = GetEntityY()},
--    	},
--    	Actions =
--    	{
-- 			ObjectChange	{Tag = "OrogLight05", ObjectId = LightId, X = GetEntityX(), Y = GetEntityY()},
-- 			MapFlagSetTrue {Name = "mf_OrogLight05On"},
-- 			FigureVanish	{Tag = "OrogLight05burner"},
-- 			MapTimerStop	{Name = "mt_Burner05generateTimer"},
--   		},
--    },    
-- 
--
--};
