--State
--{	
--	StateName = "INIT",
--	OnFigureSpawnOnlyWhenEvent	
--	{
--		X = GetEntityX(),
--		Y = GetEntityY(),
--		NoSpawnEffect = true, 
--		Conditions =
--		{
--			MapFlagIsTrue {Name = "mf_CS_04_Orcs_Spawn"},
--		},
--		Actions = 
--		{
--		},
--		DelayedActions = 
--		{
--			CutsceneFigureTeleport {Tag = "default", X = 438.2, Y = 469, },			
--			FigureLookAtDirection {Tag = "default", Direction = 0},
--			FigureCutsceneTalkJobSet {Tag = "default"},
--			CutsceneFigureWeaponsHide {Tag = "default"},
--		},
--	},
--};