--State
--{
--	StateName = "INIT",
--	OnFigureSpawnOnlyWhenEvent
--	{
--		X = GetEntityX(),
--		Y = GetEntityY(),
--		NoSpawnEffect = true,
--		Conditions = 
--		{
--			MapFlagIsTrue {Name = "mf_CS_05_Actors_Spawn"},
--		},
--		Actions = 
--		{
--		},
--		DelayedActions = 
--		{
--			CutsceneFigureTeleport {Tag = "default", X = 128.72, Y = 546.455, },
--			FigureLookAtDirection {Tag = "default", Direction = 300},
--		},
--	};
--}
