--*******************************************************
--***                                                 ***
--***               Palace Addon1					  ***
--***			    ElementalMage	                  ***
--***                                                 ***
--*******************************************************


--State
--{	
--	StateName = "InitState",
--	OnOneTimeEvent
--	{
--		Conditions =
--		{
--			BuildingIsDead	{Tag = "EarthBase"},
--			BuildingIsDead	{Tag = "FireBase"},
--			BuildingIsDead	{Tag = "WindBase"},
--			BuildingIsDead	{Tag = "IceBae"},
--			
--		},
--		Actions =
--		{
--			FigureTeleport	{X = 85, Y = 232},
--			EffectStart	{Tag = "ElementalMage", File = "Effect_DeSpawn_Unit"},
--		},
--		
--	},
--	
--	
--};