State
{
  StateName = "SPAWN",

  OnFigureRespawnEvent
  {
    WaitTime = 1,
    X = 522,
    Y = 386,
    Conditions =
    {
    },
    Actions =
    {
      FigureWalk {Tag = "Clan1", X = GetEntityX(), Y = GetEntityY()},
      FigureWalk {Tag = "Clan2", X = GetEntityX(), Y = GetEntityY()},
      FigureWalk {Tag = "Clan3", X = GetEntityX(), Y = GetEntityY()},
      FigureWalk {Tag = "Clan4", X = GetEntityX(), Y = GetEntityY()},
      FigureWalk {Tag = "Clan5", X = GetEntityX(), Y = GetEntityY()},
      FigureWalk {Tag = "Clan6", X = GetEntityX(), Y = GetEntityY()},
      FigureWalk {Tag = "Clan7", X = GetEntityX(), Y = GetEntityY()},
      FigureWalk {Tag = "Clan8", X = GetEntityX(), Y = GetEntityY()},
      FigureWalk {Tag = "Clan9", X = GetEntityX(), Y = GetEntityY()},
      FigureWalk {Tag = "Clan10", X = GetEntityX(), Y = GetEntityY()},
      FigureWalk {Tag = "Clan11", X = GetEntityX(), Y = GetEntityY()},
      FigureWalk {Tag = "Clan12", X = GetEntityX(), Y = GetEntityY()},
      FigureWalk {Tag = "Clan13", X = GetEntityX(), Y = GetEntityY()},
      FigureWalk {Tag = "Clan14", X = GetEntityX(), Y = GetEntityY()},
      FigureWalk {Tag = "Clan15", X = GetEntityX(), Y = GetEntityY()},
      FigureWalk {Tag = "Clan16", X = GetEntityX(), Y = GetEntityY()},
      FigureWalk {Tag = "Clan17", X = GetEntityX(), Y = GetEntityY()},
      FigureWalk {Tag = "Clan18", X = GetEntityX(), Y = GetEntityY()},
      FigureWalk {Tag = "Clan19", X = GetEntityX(), Y = GetEntityY()},
      FigureWalk {Tag = "Clan20", X = GetEntityX(), Y = GetEntityY()},
      FigureWalk {Tag = "Clan21", X = GetEntityX(), Y = GetEntityY()},
      FigureWalk {Tag = "Clan22", X = GetEntityX(), Y = GetEntityY()},
      FigureWalk {Tag = "Clan23", X = GetEntityX(), Y = GetEntityY()},
      FigureWalk {Tag = "Clan24", X = GetEntityX(), Y = GetEntityY()},
      FigureWalk {Tag = "Clan25", X = GetEntityX(), Y = GetEntityY()},
      FigureWalk {Tag = "Clan26", X = GetEntityX(), Y = GetEntityY()},
      FigureWalk {Tag = "Clan27", X = GetEntityX(), Y = GetEntityY()},
      FigureWalk {Tag = "Clan28", X = GetEntityX(), Y = GetEntityY()},
      FigureWalk {Tag = "Clan29", X = GetEntityX(), Y = GetEntityY()},
      FigureWalk {Tag = "Clan30", X = GetEntityX(), Y = GetEntityY()},
      FigureWalk {Tag = "Clan31", X = GetEntityX(), Y = GetEntityY()},
      FigureWalk {Tag = "Clan32", X = GetEntityX(), Y = GetEntityY()},
      FigureWalk {Tag = "Clan33", X = GetEntityX(), Y = GetEntityY()},
      FigureWalk {Tag = "Clan34", X = GetEntityX(), Y = GetEntityY()},
      FigureWalk {Tag = "Clan35", X = GetEntityX(), Y = GetEntityY()},
      FigureWalk {Tag = "Clan36", X = GetEntityX(), Y = GetEntityY()},
      FigureWalk {Tag = "Clan37", X = GetEntityX(), Y = GetEntityY()},
      FigureWalk {Tag = "Clan38", X = GetEntityX(), Y = GetEntityY()},
      FigureWalk {Tag = "Clan39", X = GetEntityX(), Y = GetEntityY()},
      FigureWalk {Tag = "Clan40", X = GetEntityX(), Y = GetEntityY()},
      FigureWalk {Tag = "Clan41", X = GetEntityX(), Y = GetEntityY()},
      FigureWalk {Tag = "Clan42", X = GetEntityX(), Y = GetEntityY()},
      FigureWalk {Tag = "Clan43", X = GetEntityX(), Y = GetEntityY()},
      FigureWalk {Tag = "Clan44", X = GetEntityX(), Y = GetEntityY()},
      FigureWalk {Tag = "Clan45", X = GetEntityX(), Y = GetEntityY()},
      FigureWalk {Tag = "Clan46", X = GetEntityX(), Y = GetEntityY()},
      FigureWalk {Tag = "Clan47", X = GetEntityX(), Y = GetEntityY()},
      FigureWalk {Tag = "Clan48", X = GetEntityX(), Y = GetEntityY()},
      FigureWalk {Tag = "Clan49", X = GetEntityX(), Y = GetEntityY()},
      FigureWalk {Tag = "Clan50", X = GetEntityX(), Y = GetEntityY()},
      FigureWalk {Tag = "Clan51", X = GetEntityX(), Y = GetEntityY()},
      FigureWalk {Tag = "Clan52", X = GetEntityX(), Y = GetEntityY()},
      FigureWalk {Tag = "Clan53", X = GetEntityX(), Y = GetEntityY()},
      FigureWalk {Tag = "Clan54", X = GetEntityX(), Y = GetEntityY()},
      FigureWalk {Tag = "Clan55", X = GetEntityX(), Y = GetEntityY()},
      FigureWalk {Tag = "Clan56", X = GetEntityX(), Y = GetEntityY()},
      FigureWalk {Tag = "Clan57", X = GetEntityX(), Y = GetEntityY()},
      FigureWalk {Tag = "Clan58", X = GetEntityX(), Y = GetEntityY()},
      FigureWalk {Tag = "Clan59", X = GetEntityX(), Y = GetEntityY()},
      FigureWalk {Tag = "Clan60", X = GetEntityX(), Y = GetEntityY()},
      FigureWalk {Tag = "Clan61", X = GetEntityX(), Y = GetEntityY()},
      FigureWalk {Tag = "Clan62", X = GetEntityX(), Y = GetEntityY()},
    },
  };
};
