---------------------------------------------------------------------------------
----
----		3. Cutscene:
----
----		Avatar hat das Klangrätsel gelöst
----
----		Nun sind die drei Freunde vor dem Labor
----
---------------------------------------------------------------------------------
--
--
--State
--{
--	StateName = "INITCutscene",
--	OnOneTimeEvent
--	{
--		GotoState = "Main",
--		Conditions =
--		{
--		},
--		Actions =
--		{
--		},
--	},
--}
--
--State
--{
--	StateName = "Main",
--	OnOneTimeEvent
--	{
--		Conditions =
--		{
--			AvatarFlagIsTrue {Name = "af_P319_Cutscene03Begin"},
--		},
--		Actions =
--		{
--			CutsceneBegin {},
--			CameraSet {X = 298.01, Y = 121.56, Z = 497.78, LookAtX = 298.01, LookAtY = 120.62, LookAtZ = 498.13},
--			EntityTimerStart {Name = "et_Cutscene"},	
--		}
--	},
--	
--	
--	OnOneTimeEvent
--	{
--		Conditions =
--		{
--			EntityTimerIsElapsed {Name = "et_Cutscene", Seconds = 5},
--		},
--		Actions =
--		{
--			CutsceneSay	{TextTag = "Lab_01", Tag = "pl_HumanAvatar"},
--			
--		}
--	},
--
--	OnOneTimeEvent
--	{
--		Conditions =
--		{
--			EntityTimerIsElapsed {Name = "et_Cutscene", Seconds = 10},
--		},
--		Actions =
--		{
--			CutsceneSay	{TextTag = "Lab_02", Tag = "Schattenkrieger"},
--			
--		}
--	},
--
--	OnOneTimeEvent
--	{
--		Conditions =
--		{
--			EntityTimerIsElapsed {Name = "et_Cutscene", Seconds = 15},
--		},
--		Actions =
--		{
--			CutsceneSay	{TextTag = "Lab_03", Tag = "Schattenkrieger"},
--			
--		}
--	},
--
--	OnOneTimeEvent
--	{
--		Conditions =
--		{
--			EntityTimerIsElapsed {Name = "et_Cutscene", Seconds = 20},
--		},
--		Actions =
--		{
--			CutsceneSay	{TextTag = "Lab_04", Tag = "Schattenkrieger"},
--			
--		}
--	},
--
--	OnOneTimeEvent
--	{
--		Conditions =
--		{
--			EntityTimerIsElapsed {Name = "et_Cutscene", Seconds = 25},
--		},
--		Actions =
--		{
--			CutsceneSay	{TextTag = "Lab_05", Tag = "pl_HumanAvatar"},
--			
--		}
--	},
--
--	OnOneTimeEvent
--	{
--			Conditions =
--			{
--				EntityTimerIsElapsed {Name = "et_Cutscene", Seconds = 30},
--			},
--			Actions =
--			{	
--				CameraStop {},
--				CutsceneEnd {},
--				
--				AvatarFlagSetTrue {Name = "af_P319_CS03Finished"},
--			},
--	},
--	
--}
