---------------------------------------------------------------------------------
----
----		2. Cutscene:
----
----		Portal wird entdeckt
----
---------------------------------------------------------------------------------
--
--
--State
--{
--	StateName = "INITCutscene",
--	OnOneTimeEvent
--	{
--		GotoState = "Main",
--		Conditions =
--		{
--		},
--		Actions =
--		{
--		},
--	},
--}
--
--State
--{
--	StateName = "Main",
--	OnOneTimeEvent
--	{
--		Conditions =
--		{
--			AvatarFlagIsTrue {Name = "af_P312_CS02Start"},
--		},
--		Actions =
--		{
--			CutsceneBegin {},
--			CameraSet {X = 165.09, Y = 77.87, Z = 262.10, LookAtX = 165.09, LookAtY = 76.93, LookAtZ = 262.44},
--			EntityTimerStart {Name = "et_Cutscene"},	
--		}
--	},
--	
--	
--	OnOneTimeEvent
--	{
--		Conditions =
--		{
--			EntityTimerIsElapsed {Name = "et_Cutscene", Seconds = 5},
--		},
--		Actions =
--		{
--			CutsceneSay	{TextTag = "PortalFound_01", Tag = "pl_HumanAvatar"},
--			
--		}
--	},
--
--
--
--	OnOneTimeEvent
--	{
--			Conditions =
--			{
--				EntityTimerIsElapsed {Name = "et_Cutscene", Seconds = 10},
--			},
--			Actions =
--			{	
--				CameraStop {},
--				CutsceneEnd {},
--				
--				AvatarFlagSetTrue {Name = "af_P312_CS02Finished"},
--			},
--	},
--	
--}
